name: buckle2000的个人网站

# Where things are
collections:
  posts:
    output: true
    permalink: /post/:path
  articles:
    output: true
    permalink: /article/:path

# Plugins
# whitelist: []
# gems:      []


# Outputting
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      # tag: default
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: post
      tag: default

# Exclude these files from your production _site
exclude:
  - ".gitignore"
  - "README.md"
  - "*.sublime-*"

sass:
    sass_dir: _sass
    style: compressed