# Plugins
# whitelist: []
# gems:      []

# Outputting
permalink: /:path/:name

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: post #TODO

collections:
  posts:
    output:   true
  articles:
    output: true
    permalink: /:collection/:path/

# Exclude these files from your production _site
exclude:
  - ".gitignore"
  - "README.md"
