# Where things are
collections:
  posts:
    output:   true
  articles:
    output: true
    permalink: /:collection/:path/

# Plugins
# whitelist: []
# gems:      []


# Outputting
permalink: /:path/:name
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: post #TODO

# Exclude these files from your production _site
exclude:
  - ".gitignore"
  - "README.md"

sass:
    sass_dir: _sass
    style: compressed